<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateMeansTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('means', function (Blueprint $table) {
            $table->id();
            $table->foreignId('portfolio_id')->constrained()->onDelete('cascade')->onUpdate('cascade');
            $table->boolean('fl_matriz')->nullable();
            $table->string('de_natureza_juridica')->nullable();
            $table->string('sg_uf')->nullable();
            $table->string('natureza_juridica_macro')->nullable();
            $table->string('de_ramo')->nullable();
            $table->string('setor')->nullable();
            $table->float('idade_empresa_anos')->nullable();
            $table->string('idade_emp_cat')->nullable();
            $table->boolean('fl_me')->nullable();
            $table->boolean('fl_sa')->nullable();
            $table->boolean('fl_epp')->nullable();
            $table->boolean('fl_mei')->nullable();
            $table->boolean('fl_ltda')->nullable();
            $table->date('dt_situacao')->nullable();
            $table->boolean('fl_st_especial')->nullable();
            $table->boolean('fl_email')->nullable();
            $table->boolean('fl_telefone')->nullable();
            $table->boolean('fl_rm')->nullable();
            $table->string('nm_divisao')->nullable();
            $table->string('nm_segmento')->nullable();
            $table->boolean('fl_spa')->nullable();
            $table->boolean('fl_antt')->nullable();
            $table->boolean('fl_veiculo')->nullable();
            $table->float('vl_total_tancagem')->nullable();
            $table->float('vl_total_veiculos_antt')->nullable();
            $table->float('vl_total_veiculos_leves')->nullable();
            $table->float('vl_total_veiculos_pesados')->nullable();
            $table->boolean('fl_optante_simples')->nullable();
            $table->float('qt_art')->nullable();
            $table->float('vl_total_veiculos_pesados_grupo')->nullable();
            $table->float('vl_total_veiculos_leves_grupo')->nullable();
            $table->float('vl_total_tancagem_grupo')->nullable();
            $table->float('vl_total_veiculos_antt_grupo')->nullable();
            $table->float('vl_potenc_cons_oleo_gas')->nullable();
            $table->boolean('fl_optante_simei')->nullable();
            $table->string('sg_uf_matriz')->nullable();
            $table->string('de_saude_tributaria')->nullable();
            $table->string('de_saude_rescencia')->nullable();
            $table->float('nu_meses_rescencia')->nullable();
            $table->string('de_nivel_atividade')->nullable();
            $table->string('de_indicador_telefone')->nullable();
            $table->boolean('fl_simples_irregular')->nullable();
            $table->double('vl_frota')->nullable();
            $table->float('empsetorcensitariofaixarendapopulacao')->nullable();
            $table->string('nm_meso_regiao')->nullable();
            $table->string('nm_micro_regiao')->nullable();
            $table->boolean('fl_passivel_iss')->nullable();
            $table->float('qt_socios')->nullable();
            $table->float('qt_socios_pf')->nullable();
            $table->float('qt_socios_pj')->nullable();
            $table->float('idade_media_socios')->nullable();
            $table->float('idade_maxima_socios')->nullable();
            $table->float('idade_minima_socios')->nullable();
            $table->float('qt_socios_st_regular')->nullable();
            $table->float('qt_socios_st_suspensa')->nullable();
            $table->float('qt_socios_masculino')->nullable();
            $table->float('qt_socios_feminino')->nullable();
            $table->float('qt_socios_pep')->nullable();
            $table->float('qt_alteracao_socio_total')->nullable();
            $table->float('qt_alteracao_socio_90d')->nullable();
            $table->float('qt_alteracao_socio_180d')->nullable();
            $table->float('qt_alteracao_socio_365d')->nullable();
            $table->float('qt_socios_pj_ativos')->nullable();
            $table->float('qt_socios_pj_nulos')->nullable();
            $table->float('qt_socios_pj_baixados')->nullable();
            $table->float('qt_socios_pj_suspensos')->nullable();
            $table->float('qt_socios_pj_inaptos')->nullable();
            $table->float('vl_idade_media_socios_pj')->nullable();
            $table->float('vl_idade_maxima_socios_pj')->nullable();
            $table->float('vl_idade_minima_socios_pj')->nullable();
            $table->float('qt_coligados')->nullable();
            $table->float('qt_socios_coligados')->nullable();
            $table->float('qt_coligados_matriz')->nullable();
            $table->float('qt_coligados_ativo')->nullable();
            $table->float('qt_coligados_baixada')->nullable();
            $table->float('qt_coligados_inapta')->nullable();
            $table->float('qt_coligados_suspensa')->nullable();
            $table->float('qt_coligados_nula')->nullable();
            $table->float('idade_media_coligadas')->nullable();
            $table->float('idade_maxima_coligadas')->nullable();
            $table->float('idade_minima_coligadas')->nullable();
            $table->float('coligada_mais_nova_ativa')->nullable();
            $table->float('coligada_mais_antiga_ativa')->nullable();
            $table->float('idade_media_coligadas_ativas')->nullable();
            $table->float('coligada_mais_nova_baixada')->nullable();
            $table->float('coligada_mais_antiga_baixada')->nullable();
            $table->float('idade_media_coligadas_baixadas')->nullable();
            $table->float('qt_coligados_sa')->nullable();
            $table->float('qt_coligados_me')->nullable();
            $table->float('qt_coligados_mei')->nullable();
            $table->float('qt_coligados_ltda')->nullable();
            $table->float('qt_coligados_epp')->nullable();
            $table->float('qt_coligados_norte')->nullable();
            $table->float('qt_coligados_sul')->nullable();
            $table->float('qt_coligados_nordeste')->nullable();
            $table->float('qt_coligados_centro')->nullable();
            $table->float('qt_coligados_sudeste')->nullable();
            $table->float('qt_coligados_exterior')->nullable();
            $table->float('qt_ufs_coligados')->nullable();
            $table->float('qt_regioes_coligados')->nullable();
            $table->float('qt_ramos_coligados')->nullable();
            $table->float('qt_coligados_industria')->nullable();
            $table->float('qt_coligados_agropecuaria')->nullable();
            $table->float('qt_coligados_comercio')->nullable();
            $table->float('qt_coligados_serviço')->nullable();
            $table->float('qt_coligados_ccivil')->nullable();
            $table->float('qt_funcionarios_coligados')->nullable();
            $table->float('qt_funcionarios_coligados_gp')->nullable();
            $table->float('media_funcionarios_coligados_gp')->nullable();
            $table->float('max_funcionarios_coligados_gp')->nullable();
            $table->float('min_funcionarios_coligados_gp')->nullable();
            $table->double('vl_folha_coligados')->nullable();
            $table->double('media_vl_folha_coligados')->nullable();
            $table->double('max_vl_folha_coligados')->nullable();
            $table->double('min_vl_folha_coligados')->nullable();
            $table->double('vl_folha_coligados_gp')->nullable();
            $table->double('media_vl_folha_coligados_gp')->nullable();
            $table->double('max_vl_folha_coligados_gp')->nullable();
            $table->double('min_vl_folha_coligados_gp')->nullable();
            $table->double('faturamento_est_coligados')->nullable();
            $table->double('media_faturamento_est_coligados')->nullable();
            $table->double('max_faturamento_est_coligados')->nullable();
            $table->double('min_faturamento_est_coligados')->nullable();
            $table->double('faturamento_est_coligados_gp')->nullable();
            $table->double('media_faturamento_est_coligados_gp')->nullable();
            $table->double('max_faturamento_est_coligados_gp')->nullable();
            $table->double('min_faturamento_est_coligados_gp')->nullable();
            $table->float('total_filiais_coligados')->nullable();
            $table->float('media_filiais_coligados')->nullable();
            $table->float('max_filiais_coligados')->nullable();
            $table->float('min_filiais_coligados')->nullable();
            $table->float('qt_coligados_atividade_alto')->nullable();
            $table->float('qt_coligados_atividade_medio')->nullable();
            $table->float('qt_coligados_atividade_baixo')->nullable();
            $table->float('qt_coligados_atividade_mt_baixo')->nullable();
            $table->float('qt_coligados_atividade_inativo')->nullable();
            $table->float('qt_coligadas')->nullable();
            $table->double('sum_faturamento_estimado_coligadas')->nullable();
            $table->string('de_faixa_faturamento_estimado')->nullable();
            $table->string('de_faixa_faturamento_estimado_grupo')->nullable();
            $table->double('vl_faturamento_estimado_aux')->nullable();
            $table->double('vl_faturamento_estimado_grupo_aux')->nullable();
            $table->double('qt_ex_funcionarios')->nullable();
            $table->double('qt_funcionarios_grupo')->nullable();
            $table->float('percent_func_genero_masc')->nullable();
            $table->float('percent_func_genero_fem')->nullable();
            $table->float('idade_ate_18')->nullable();
            $table->float('idade_de_19_a_23')->nullable();
            $table->float('idade_de_24_a_28')->nullable();
            $table->float('idade_de_29_a_33')->nullable();
            $table->float('idade_de_34_a_38')->nullable();
            $table->float('idade_de_39_a_43')->nullable();
            $table->float('idade_de_44_a_48')->nullable();
            $table->float('idade_de_49_a_53')->nullable();
            $table->float('idade_de_54_a_58')->nullable();
            $table->float('idade_acima_de_58')->nullable();
            $table->float('grau_instrucao_macro_analfabeto')->nullable();
            $table->float('grau_instrucao_macro_escolaridade_fundamental')->nullable();
            $table->float('grau_instrucao_macro_escolaridade_media')->nullable();
            $table->float('grau_instrucao_macro_escolaridade_superior')->nullable();
            $table->float('grau_instrucao_macro_desconhecido')->nullable();
            $table->float('total')->nullable();
            $table->float('meses_ultima_contratacaco')->nullable();
            $table->float('qt_admitidos_12meses')->nullable();
            $table->float('qt_desligados_12meses')->nullable();
            $table->float('qt_desligados')->nullable();
            $table->float('qt_admitidos')->nullable();
            $table->float('media_meses_servicos_all')->nullable();
            $table->float('max_meses_servicos_all')->nullable();
            $table->float('min_meses_servicos_all')->nullable();
            $table->float('media_meses_servicos')->nullable();
            $table->float('max_meses_servicos')->nullable();
            $table->float('min_meses_servicos')->nullable();
            $table->float('qt_funcionarios')->nullable();
            $table->float('qt_funcionarios_12meses')->nullable();
            $table->float('qt_funcionarios_24meses')->nullable();
            $table->float('tx_crescimento_12meses')->nullable();
            $table->float('tx_crescimento_24meses')->nullable();
            $table->float('tx_rotatividade')->nullable();
            $table->float('qt_filiais')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('means');
    }
}
